sonar.projectKey=kanban-react-app
sonar.projectName=Kanban React App
sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://3.134.115.197:9000
sonar.token=sqp_92a1a1b2ef6a620aea538b58f6aeec1ca504e3fc

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/*.png

